export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const SET_PRODUCT_REQUEST = "SET_PRODUCT_REQUEST";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_DEVELOPMENT_BOARDS_REQUEST = "GET_DEVELOPMENT_BOARDS_REQUEST"
export const GET_DEVELOPMENT_BOARD_REQUEST = "GET_DEVELOPMENT_BOARD_REQUEST";
export const GET_ACCESSORIES_REQUEST = "GET_ACCESSORIES_REQUEST";